#!/usr/bin/env bats
load '../test_helper'

setup() {
    source "$LIB_DIR/xrayconf.sh"
}

@test "build_outbound: reality -> realitySettings + flow" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","network":"tcp","flow":"xtls-rprx-vision","sni":"cdn.example.com","fingerprint":"firefox","public_key":"PBK","short_id":"sid1"}'
    run xrayconf_build_outbound <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.security')" = "reality" ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.realitySettings.publicKey')" = "PBK" ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.realitySettings.serverName')" = "cdn.example.com" ]
    [ "$(printf '%s' "$output" | jq -r '.settings.vnext[0].users[0].flow')" = "xtls-rprx-vision" ]
}

@test "build_outbound: tls -> tlsSettings serverName from sni" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"tls","sni":"host.example.com","fingerprint":"chrome"}'
    run xrayconf_build_outbound <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.security')" = "tls" ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.tlsSettings.serverName')" = "host.example.com" ]
}

@test "build_outbound: tls -> alpn emitted when present" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"tls","sni":"host.example.com","alpn":["h2","http/1.1"]}'
    run xrayconf_build_outbound <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.tlsSettings.alpn | join(",")')" = "h2,http/1.1" ]
}

@test "build_outbound: legacy (no security) -> tls alpn h2, no flow" {
    server='{"address":"example.com","port":443,"uuid":"u1","flow":"xtls-rprx-vision"}'
    run xrayconf_build_outbound <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.security')" = "tls" ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.tlsSettings.serverName')" = "example.com" ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.tlsSettings.alpn[0]')" = "h2" ]
    [ "$(printf '%s' "$output" | jq -r '.settings.vnext[0].users[0] | has("flow")')" = "false" ]
}

# The Go generator takes the legacy serverName from the sni when there is one:
# the subscription watch dials a resolved IP and keeps the hostname there. The
# same server generated by configure.sh has to name the same host.
@test "build_outbound: legacy (no security) with an sni -> serverName from the sni" {
    server='{"address":"203.0.113.50","port":443,"uuid":"u1","sni":"example.com"}'
    run xrayconf_build_outbound <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.tlsSettings.serverName')" = "example.com" ]
}

@test "build_outbound: unsupported network -> error" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","network":"ws","sni":"s","public_key":"PBK","short_id":"sid"}'
    run xrayconf_build_outbound <<< "$server"
    [ "$status" -ne 0 ]
}

@test "build_outbound: unsupported security -> error" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"xtls"}'
    run xrayconf_build_outbound <<< "$server"
    [ "$status" -ne 0 ]
}

@test "generate: replaces outbounds and preserves inbounds/routing" {
    tmpl="$BATS_TEST_TMPDIR/t.json"
    printf '%s' '{"inbounds":[{"tag":"tproxy-in"},{"tag":"socks-in"}],"outbounds":[],"routing":{"rules":[{"outboundTag":"proxy-out"}]}}' > "$tmpl"
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","sni":"s","fingerprint":"firefox","public_key":"PBK","short_id":"sid"}'
    run xrayconf_generate "$tmpl" <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.outbounds[0].streamSettings.security')" = "reality" ]
    [ "$(printf '%s' "$output" | jq -r '.outbounds | length')" = "1" ]
    # inbounds/routing from the template must be preserved untouched
    [ "$(printf '%s' "$output" | jq -r '.inbounds | length')" = "2" ]
    [ "$(printf '%s' "$output" | jq -r '.routing.rules[0].outboundTag')" = "proxy-out" ]
}

@test "build_outbound: empty/null/non-object input -> error (no silent null outbound)" {
    run xrayconf_build_outbound <<< ""
    [ "$status" -ne 0 ]
    run xrayconf_build_outbound <<< "null"
    [ "$status" -ne 0 ]
    run xrayconf_build_outbound <<< '{"port":443}'
    [ "$status" -ne 0 ]
}

@test "generate: returns non-zero on unsupported security (caller must not truncate)" {
    tmpl="$BATS_TEST_TMPDIR/t.json"
    printf '%s' '{"outbounds":[]}' > "$tmpl"
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"xtls"}'
    run xrayconf_generate "$tmpl" <<< "$server"
    [ "$status" -ne 0 ]
}

@test "build_outbound: reality missing public_key/sni/fingerprint -> error" {
    run xrayconf_build_outbound <<< '{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","sni":"s","fingerprint":"firefox"}'
    [ "$status" -ne 0 ]
    run xrayconf_build_outbound <<< '{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","public_key":"P","fingerprint":"firefox"}'
    [ "$status" -ne 0 ]
    run xrayconf_build_outbound <<< '{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","public_key":"P","sni":"s"}'
    [ "$status" -ne 0 ]
}

@test "build_outbound: reality without short_id (optional) -> ok" {
    run xrayconf_build_outbound <<< '{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","public_key":"P","sni":"s","fingerprint":"firefox"}'
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.realitySettings.publicKey')" = "P" ]
    [ "$(printf '%s' "$output" | jq -r '.streamSettings.realitySettings | has("shortId")')" = "false" ]
}

@test "generate: real template keeps the log section" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"reality","sni":"s","fingerprint":"firefox","public_key":"PBK","short_id":"sid"}'
    run xrayconf_generate "$PROJECT_ROOT/opt/etc/xray/config.json.template" <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.log.error')" = "/tmp/xray-error.log" ]
    [ "$(printf '%s' "$output" | jq -r '.outbounds | length')" = "1" ]
}

@test "generate: given ports, the inbounds follow advanced.xray" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"tls","sni":"s","fingerprint":"chrome"}'
    run xrayconf_generate "$PROJECT_ROOT/opt/etc/xray/config.json.template" 23456 23457 <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.inbounds[] | select(.tag == "tproxy-in") | .port')" = "23456" ]
    [ "$(printf '%s' "$output" | jq -r '.inbounds[] | select(.tag == "socks-in") | .port')" = "23457" ]
}

@test "generate: without ports the template values stay" {
    server='{"address":"1.2.3.4","port":443,"uuid":"u1","security":"tls","sni":"s","fingerprint":"chrome"}'
    run xrayconf_generate "$PROJECT_ROOT/opt/etc/xray/config.json.template" <<< "$server"
    [ "$status" -eq 0 ]
    [ "$(printf '%s' "$output" | jq -r '.inbounds[] | select(.tag == "tproxy-in") | .port')" = "12345" ]
    [ "$(printf '%s' "$output" | jq -r '.inbounds[] | select(.tag == "socks-in") | .port')" = "12346" ]
}
