#!/bin/bash
case "$*" in
    "get ipv6_service") echo "native" ;;
    "get wan0_primary") echo "1" ;;
    "get wan0_ifname")  echo "eth0" ;;
    "get wan1_primary") echo "0" ;;
    "get wan1_ifname")  echo "eth1" ;;
    "get model")        echo "RT-AX88U" ;;
    "get vpn_client1_addr") echo "openvpn1.example.com" ;;
    "get vpn_client2_addr") echo "" ;;
    "get vpn_client3_addr") echo "example.com" ;;
    "get vpn_client4_addr") echo "" ;;
    "get vpn_client5_addr") echo "" ;;
    "get vpn_client1_rgw") echo "2" ;;
    "get vpn_client2_rgw") echo "2" ;;
    "get lan_ipaddr")   [ "${NVRAM_NO_LAN_IP:-0}" = "1" ] && echo "" || echo "192.168.50.1" ;;
    "get lan_hostname") echo "RT-AX88U-1234" ;;
    "get wgc1_desc")    echo "Office WG" ;;
    "get vpn_client1_desc") echo "Office OVPN" ;;
    *) echo "" ;;
esac
